### ISSUE TITLE
Problemas de layout no desktop

### ISSUE THREAD

**Issue by juanpinheiro** [Unacon/StreetFighter#3]
Organização da apresentação dos personagens

![image](https://user-images.githubusercontent.com/8218229/112074613-74068f00-8b55-11eb-8c5e-27f3517698eb.png)

Espaçamento no footer está muito grande

![image](https://user-images.githubusercontent.com/8218229/112074654-88e32280-8b55-11eb-8341-b66cf7011137.png)

**Comment by juanpinheiro** [comment]
Usar um max-width pode ajudar em monitores grandes.

```html
<section class="characters">
    <div class="container">
            ...
    </div>
</section>
```

```css
.container {
    width: 100%;
    max-width: 1280px;
    margin: 0 auto;
    ...
}

```
